#!G:\Meu Drive\Cursos e Treinamentos\Cientista de Dados\Treinamento Python\I2A2\Desafios\Insurminds\Desafio 2\agente_chatbotseguro\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
