name: Docker Image CI

on:
  push:
    branches: [ "master" ] 
        

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          # github.repository_owner = ajndantas
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/agente_nfs
          #IMAGE_ID=agente_nfs
          #TAG=$(date +%Y%m%d%H%M%S)
          TAG=latest
          docker build --build-arg GOOGLE_API_KEY="AIzaSyAOhPIBGBJyhmQFGwcuMxGqS0MniA_7TQ8" -t $IMAGE_ID:$TAG "Desafio 2 - Projeto - 11062025/agente_nfs/Scripts/"
          docker push $IMAGE_ID:$TAG
          