name: Docker Image CI agente_eda

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'Desafio Extra Fraude Cartao de Credito/agente_fraude_cartao/**'        

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          # github.repository_owner = ajndantas
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/agente_fraude_cartao
          #TAG=$(date +%Y%m%d%H%M%S)
          TAG=latest
          docker build --build-arg API_KEY="${{ secrets.API_KEY }}" --build-arg ="${{ secrets.API_KEY_OPENROUTER }}" -t $IMAGE_ID:$TAG "Desafio Extra Fraude Cartao de Credito/agente_fraude_cartao/Scripts" # PEGA O DOCKERFILE AQUI
          docker push $IMAGE_ID:$TAG       