name: Docker Image CI agente_eda

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'Desafio Extra Fraude Cartao de Credito/agente_fraude_cartao/**'

env:
  API_KEY: ${{ secrets.API_KEY }} # DEFINA SUA API KEY AQUI, ELA VAI SER USADA PARA AUTENTICAR AS REQUISIÇÕES PARA A LLM E SERÁ USADA PELO DOCKER COMPOSE E COMANDOS SSH
  API_KEY_OPENROUTER: ${{ secrets.API_KEY_OPENROUTER }} # DEFINA SUA API KEY AQUI, ELA VAI SER USADA PARA AUTENTICAR AS REQUISIÇÕES PARA A LLM E SERÁ USADA PELO DOCKER COMPOSE E COMANDOS SSH

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          # github.repository_owner = ajndantas
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/agente_fraude_cartao
          #TAG=$(date +%Y%m%d%H%M%S)
          TAG=latest
          docker build --build-arg API_KEY="${{ secrets.API_KEY }}" --build-arg API_KEY_OPENROUTER="${{ secrets.API_KEY_OPENROUTER }}" -t $IMAGE_ID:$TAG "Desafio Extra Fraude Cartao de Credito/agente_fraude_cartao/Scripts" # PEGA O DOCKERFILE AQUI
          docker push $IMAGE_ID:$TAG    

      - name: Executar comandos via SSH na VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          debug: true
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          envs: API_KEY, API_KEY_OPENROUTER # EXPORTA A VARIÁVEL DE AMBIENTE
          script: |
            # Exporte a variável para que o Docker Compose consiga visualizá-la
            export API_KEY=$API_KEY
            export API_KEY_OPENROUTER=$API_KEY_OPENROUTER

            echo "Entrando no diretório do projeto"
            cd ~/agentes

            echo "Parando container"
            docker compose down agente_eda nginx # PARA PARAR O NGINX TAMBÉM, POIS ELE DEPENDE DO AGENTE E PRECISA SER REINICIADO PARA PEGAR AS ATUALIZAÇÕES

            echo "Removendo imagem antiga"
            docker image rm -f ghcr.io/ajndantas/agente_fraude_cartao:latest || true

            echo "Subindo container atualizado"
            docker compose up -d agente_eda nginx # SOBE O NGINX TAMBÉM, POIS ELE DEPENDE DO AGENTE E PRECISA SER REINICIADO PARA PEGAR AS ATUALIZAÇÕES

            echo "Deploy finalizado com sucesso"
   
